<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Model;
use Doctrine\ORM\AbstractQuery;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping\ClassMetadata;
use Doctrine\ORM\OptimisticLockException;
use Doctrine\ORM\ORMException;

/**
 * ModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelRepository extends EntityRepository
{
    public function __construct(EntityManagerInterface $em, ClassMetadata $metadata = null)
    {
        parent::__construct($em,
            $metadata == null ?
                new ClassMetadata(Model::class) :
                $metadata
        );
    }

    /**
     * @param Model $model
     * @return bool
     * @throws ORMException
     */
    public function add(Model $model)
    {
        try {

            $this->_em->persist($model);
            $this->_em->flush();
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }

    /**
     * @param Model  $model
     * @return bool
     * @throws ORMException
     */
    public function delete(Model $model)
    {
        try {
            $this->_em->remove($model);
            $this->_em->flush();
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }

    /**
     * @param Model $model
     * @return bool
     * @throws ORMException
     */
    public function update(Model $model)
    {
        try {
            $this->_em->merge($model);
            $this->_em->flush();
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }

    /**
     * @param $keyword
     * @return array
     */
    public function getByKeyword($keyword): array
    {
        return $this->createQueryBuilder('m')
            ->where("m.name LIKE '%$keyword%'")
            ->orderBy('m.dateAdded', "ASC")
            ->getQuery()
            ->getResult(AbstractQuery::HYDRATE_OBJECT);
    }
}
